### ISSUE TITLE
TypeError: _build_geq1_query() missing 1 required positional argument: 'shape'

### ISSUE THREAD

**Issue by dimavrok** [Shape-Fragments/SHACL2SPARQL#1]
Hi there, 

I am trying to run the tool, following the instructions, but I am getting this error: 

Traceback (most recent call last):
  File "C:\Users\44758\SHACL2SPARQL\ssf.py", line 359, in <module>
    _cmd_frag()
  File "C:\Users\44758\SHACL2SPARQL\ssf.py", line 237, in _cmd_frag
    shape_queries.append(to_sfquery(shape, ignore_tests=False))
  File "C:\Users\44758\SHACL2SPARQL\sfquery.py", line 103, in to_sfquery
    cqp = unaryquery.to_uq(node, ignore_tests=ignore_tests)
  File "C:\Users\44758\SHACL2SPARQL\unaryquery.py", line 265, in to_uq
    subqueries.append(to_uq(child))
  File "C:\Users\44758\SHACL2SPARQL\unaryquery.py", line 294, in to_uq
    subqueries.append(to_uq(child))
  File "C:\Users\44758\SHACL2SPARQL\unaryquery.py", line 378, in to_uq
    return _build_geq1_query(path)
TypeError: _build_geq1_query() missing 1 required positional argument: 'shape'

Do you have any clue what might be going wrong? 

Thank you,
Dimitris

**Comment by MaximeJakubowski** [comment]
Hi, I only see your issue now. What was the command you executed that resulted in this error?

**Comment by namedgraph** [comment]
@MaximeJakubowski I've tried both:
```
python3 ssf.py --frag ../bkg-streaming/constraints/skos-shapes.ttl
python3 ssf.py ../bkg-streaming/constraints/skos-shapes.ttl
```
and getting the same error as the OP.

**Comment by MaximeJakubowski** [comment]
This error should be fixed with the latest commit.
